sudo: false
language: rust
rust:
  - nightly
# install travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH
# install kcov dependencies
# (useless as long as Rust coverage is a lie)
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
# FIXME: I'd like to get rid of the shell scripts. travis-cargo would need to support some "test
# all local crates" command
script:
  - |
      travis/test.sh &&
      travis-cargo --only nightly doc
after_success:
  # upload the documentation from the build with stable (automatically only actually
  # runs on the master branch, not individual PRs)
  - travis-cargo --only nightly doc-upload
env:
  global:
    # GH_SECRET for pushing the docs to the gh-pages branch automatically
    - secure: denTXvhagGLyEn84shlKbWKwOIjlRprVm0cgw1BwSHhihDHEomytvOGoMPBmqcSYb8Q6oG26WN9qd0Mdha/ue3eQ9MOugrz3fZ+oQPzWbJJ9zJWDngk3WBpY7A68jZmp3RJeI7xxBykIBojcN1lJQlPRkt1uWyYJAB0GYybWAfI=
    # we don't have a special "nightly" feature (yet!)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=
