[package]

name = "lea"
version = "0.0.1"
authors = ["jonas-schievink <jonas@schievink.net>"]
repository = "https://github.com/jonas-schievink/lea"
readme = "README.md"
description = """
A Lua-based language written in Rust
"""

[dependencies]
rustc-serialize = "*"
lazy_static = "*"
term = "*"

[dependencies.peg]
git = "https://github.com/kevinmehall/rust-peg.git"
