[package]

name = "liblea"
version = "0.0.1"
authors = ["jonas-schievink <jonas@schievink.net>"]

[dependencies]
peg = "*"

parser-combinators = "*"
phf = "*"
phf_macros = "*"

[dependencies.rustlex]
git = "https://github.com/LeoTestard/rustlex.git"

