[package]
name = "lea-num"
version = "0.0.1"
authors = ["Jonas Schievink <jonas@schievink.net>"]
license = "Apache-2.0/MIT"

[lib]
name = "lea_num"
path = "lib.rs"

[dependencies]
rustc-serialize = "0.3"
