[package]

name = "lea-vm"
version = "0.0.1"
authors = ["Jonas Schievink <jonas@schievink.net>"]

[lib]
name = "lea_vm"
path = "lib.rs"

[dependencies]
lea-core = { path = "../lea-core" }
log = "0.3"
