[package]
name = "lea-vm"
version = "0.0.1"
authors = ["Jonas Schievink <jonas@schievink.net>"]
license = "Apache-2.0/MIT"

[lib]
name = "lea_vm"
path = "lib.rs"

[dependencies]
lea-core = { path = "../lea-core" }
lea-num = { path = "../lea-num" }
lea-mem = { path = "../lea-mem" }
log = "0.3"
