[package]

name = "lea-ast"
version = "0.0.1"
authors = ["Jonas Schievink <jonas@schievink.net>"]

[lib]
name = "lea_ast"
path = "lib.rs"

[dependencies]
term = "*"
unicode-segmentation = "*"

[dependencies.lea-core]
path = "../lea-core"
